#!/usr/bin/env python3.14


from base64 import b64encode
import config
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import os
import re


os.chdir(os.path.dirname(__file__))

email_id = input("Email ID to generate: ")

config = config.config[email_id]

print(f'Generating email with subject "{config["subject"]}"...')

plain = f"""\
Ihr E-Mail-Programm stellt formatierte E-Mails leider nicht dar. Bitte lesen Sie unseren ELF-Newsletter im Browser:
{config["link"]}

Ihr Super-Service-ELF-Team\
"""

with open("template.html") as f:
	html = f.read()

with open(f"../contents/newsletter/{email_id}.html") as f:
	message = f.read().replace('href="/', 'href="https://super-service-elf.de/')
html = html.replace("messagePreviewPlaceholder", re.sub(r"<h\d>.*?</h\d>", "", message))
html = html.replace("messagePlaceholder", message)

html = html.replace("linkPlaceholder", config["link"])

for attachment in [
	("/fonts/GothamRounded.woff2", "font/woff2"),
	("/fonts/GothamRounded-Bold.woff2", "font/woff2"),
	("/images/logo-light.svg", "image/svg+xml"),
	("/images/logo-dark.svg", "image/svg+xml"),
] + config.get("attachments", []):
	with open(f"../{attachment[0]}", "rb") as f:
		html = html.replace(attachment[0], f"data:{attachment[1]};base64,{b64encode(f.read()).decode()}")


email = MIMEMultipart(
	_subtype="alternative",
	_subparts=[
		MIMEText(_text=plain, _subtype="plain"),
		MIMEText(_text=html, _subtype="html", _charset="utf-8"),
	],
)

email["From"] = "Super-Service-ELF <mail@super-service-elf.de>"
email["Subject"] = config["subject"]

with open("email.eml", "w") as f:
	f.write(email.as_string())
